[server]
port = 8501
address = "localhost"
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#FF9800"         # Safety orange
backgroundColor="#22272e"
secondaryBackgroundColor="#31363f"
textColor="#FFFFFF"
font="sans serif"